const PDFDocument =
require("pdfkit");

const knex =
require("../config/db");

const path =
require("path");

exports.generatePDF =
async (req, res) => {

  try {

    const transactions =
      await knex(
        "transactions"
      )
      .where({
        user_id:
          req.user.id,
      });

    let income = 0;
    let expenses = 0;

    transactions.forEach(
      transaction => {

        const amount =
          Number(
            transaction.amount
          );

        if (
          amount > 0
        ) {

          income += amount;

        }

        else {

          expenses +=
            Math.abs(amount);

        }

      }
    );

    const balance =
      income - expenses;

    const doc =
      new PDFDocument({

        margin: 50,

      });

    const fontPath =
      path.join(
        __dirname,
        "../../fonts/NotoSans-Regular.ttf"
      );

    doc.font(
      fontPath
    );

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=FinanceEase_Report.pdf"
    );

    doc.pipe(res);

    // TITLE
    doc
      .fillColor(
        "#16a34a"
      )
      .fontSize(22)
      .text(
        "FinanceEase Report"
      );

    doc.fillColor(
      "black"
    );

    // GENERATED DATE
    doc
      .fontSize(10)
      .fillColor(
        "gray"
      )
      .text(
        `Generated: ${
          new Date()
            .toLocaleDateString(
              "en-IN"
            )
        }`
      );

    doc.moveDown();

    // DIVIDER
    doc
      .moveTo(
        50,
        doc.y
      )
      .lineTo(
        550,
        doc.y
      )
      .stroke();

    doc.moveDown();

    // SUMMARY
    doc
      .fillColor(
        "green"
      )
      .fontSize(14)
      .text(
        `Income: ₹${income}`
      );

    doc
      .fillColor(
        "red"
      )
      .text(
        `Expenses: ₹${expenses}`
      );

    doc
      .fillColor(
        "blue"
      )
      .text(
        `Balance: ₹${balance}`
      );

    doc.fillColor(
      "black"
    );

    doc.moveDown(2);

    // TRANSACTIONS TITLE
    doc
      .fillColor(
        "#16a34a"
      )
      .fontSize(16)
      .text(
        "Transactions"
      );

    doc.fillColor(
      "black"
    );

    doc.moveDown();

    // TRANSACTIONS
    transactions.forEach(
      transaction => {

        doc
          .fontSize(12)
          .text(
            `📅 ${
              new Date(
                transaction.date
              )
              .toLocaleDateString(
                "en-IN"
              )
            }`
          );

        doc.text(
          `Category: ${
            transaction.category
          }`
        );

        doc.text(
          `Description: ${
            transaction.description
          }`
        );

        doc.text(
          `Type: ${
            transaction.type
          }`
        );

        if (
          Number(
            transaction.amount
          ) > 0
        ) {

          doc.fillColor(
            "green"
          );

        }

        else {

          doc.fillColor(
            "red"
          );

        }

        doc.text(
          `Amount: ₹${transaction.amount}`
        );

        doc.fillColor(
          "black"
        );

        doc.moveDown();

        doc
          .moveTo(
            50,
            doc.y
          )
          .lineTo(
            550,
            doc.y
          )
          .stroke();

        doc.moveDown();

      }
    );

    // FOOTER
    doc.moveDown();

    doc
      .fontSize(10)
      .fillColor(
        "gray"
      )
      .text(
        "Generated by FinanceEase",
        {
          align:
            "center",
        }
      );

    doc.end();

  }

  catch (error) {

    res.status(500).json({

      error:
        error.message,

    });

  }

};